-- large_sample.lua
-- A long Lua file (>=100 lines) exercising many productions from the provided BNF.
-- generated by ChatGPT

local function id(x)
    return x
end

local function pair(a, b)
    return {a, b}
end

local M = {}

-- simple assignment and varlist = explist
local a, b, c = 1, 2, "three"

-- table constructor with mixed fields
local t = {
    10,
    key = "value",
    [2+3] = "computed",
    nested = { x = 1, y = 2 },
}

-- function definition (global)
function M.add(x, y)
    return x + y
end

-- local function (named)
local function helper(n)
    if n <= 0 then
        return 0
    elseif n == 1 then
        return 1
    else
        return helper(n-1) + helper(n-2)
    end
end

-- function using varargs and parlist '...'
function M.collect(...)
    local out = {}
    local i = 1
    for _, v in ipairs{...} do
        out[i] = v
        i = i + 1
    end
    return out
end

-- function with method definition and method call
function M:increment(key)
    self[key] = (self[key] or 0) + 1
    return self[key]
end

local obj = { count = 0 }
obj:increment("count")

-- while loop with break and label/goto
local i = 0
while i < 5 do
    i = i + 1
    if i == 3 then
        goto skip_next
    end
    -- do a simple assignment
    local x = i * 2
    t[i] = x
    ::skip_next::
end

-- repeat ... until with return in nested block
do
    local n = 0
    repeat
        n = n + 1
        if n > 10 then
            break
        end
    until n >= 5
end

-- numeric for
for j = 1, 5, 1 do
    t[j] = (t[j] or 0) + j
end

-- generic for (for-in)
local function gen(max)
    local i = 0
    return function()
        i = i + 1
        if i <= max then return i end
    end
end

for v in gen(4) do
    t[#t+1] = v * 10
end

-- if with elseif and else blocks and nested blocks
if a < b then
    local inner = {}
    inner.value = M.add(a, b)
elseif a == b then
    local inner = {}
    inner.value = 0
else
    local inner = {}
    inner.value = -1
end

-- function call variations: prefixexp args; prefixexp : Name args
local function echo(...) return table.concat({...}, ",") end
local s = echo("one", "two", "three")
local function retTriple() return 1, 2, 3 end
local x, y, z = retTriple()

-- function definition as expression and immediate invocation
local res = (function(x) return x * x end)(7)

-- table constructor with fields and separators
local complex = {
    ["a"] = 1,
    b = 2;
    3,
    [1+1] = "two",
}

-- nested function definitions and closures
local function outer(x)
    local function inner(y)
        return x + y
    end
    return inner
end

local add5 = outer(5)
local sum = add5(10)

-- use of prefixexp '(exp)'
local val = (1 + 2) * (3 + 4)

-- function with parameters including '...'
function M.varargs_example(a, b, ...)
    local rest = {...}
    return a, b, rest
end

-- label and goto usage
local count = 0
::loop_start::
count = count + 1
if count < 3 then goto loop_start end

-- use of tableconstructor as args and LiteralString args
local tblArg = {k = "v"}
local function takesTable(t) return t.k end
local got = takesTable(tblArg)

local function takesString(s) return #s end
local slen = takesString("hello world")

-- repeat a pattern of creating fields using different field syntaxes
local fields = {
    [ "name" ] = "example",
    age = 42,
    "positional",
}

-- binary and unary operators usage
local n1 = 10 + 20 - 5 * 2
local n2 = 2^3 + 15 // 4 % 3
local n3 = -n1
local b_and = (true and false) or (false or true)

-- method-like functioncall using ':' and args
function Person(name) return {name = name} end
function Person:greet(greeting)
    return greeting .. ", " .. (self.name or "stranger")
end

local p = Person("Alice")
local greeting = p:greet("Hi")

-- for with step omitted (defaults to 1)
for k = 1, 3 do
    t[k] = tostring(k)
end

-- local namelist assignment
local x1, x2, x3 = "alpha", "beta", "gamma"

-- complex nested blocks, do ... end
do
    local a_block = {}
    do
        local inner_block = {}
        inner_block.val = "deep"
        a_block.deep = inner_block.val
    end
    t[#t+1] = a_block.deep
end

-- function that returns multiple values and retstat with semicolon
local function mult()
    return 1, 2, 3;
end

local m1, m2 = mult()

-- tableconstructor as return value
local function make_config()
    return {
        host = "localhost",
        port = 8080,
        opts = { secure = false, retries = 3 },
    }
end

local cfg = make_config()

-- longer nested if-elseif-else chain
local function classify(n)
    if n < 0 then
        return "negative"
    elseif n == 0 then
        return "zero"
    elseif n < 10 then
        return "small"
    elseif n < 100 then
        return "medium"
    else
        return "large"
    end
end

local cls = classify(42)

-- use of prefixexp as functioncall and parenthesized exp
local function wrap(x) return (x) end
local w = wrap((10 + 5))

-- chained field access using dot
local big = { sub = { inner = { value = "final" } } }
local final = big.sub.inner.value

-- function with internal while and repeat
local function counter(max)
    local i = 0
    local collected = {}
    while i < max do
        i = i + 1
        collected[i] = i * i
        if i == 4 then break end
    end
    local j = 0
    repeat
        j = j + 1
        collected[#collected+1] = j
    until j >= 2
    return collected
end

local coll = counter(6)

-- for-in with pairs to iterate a tableconstructor directly
local named = { a = 1, b = 2, c = 3 }
for k, v in pairs(named) do
    named[k] = v * 10
end

-- functioncall using tableconstructor as args
local function make_point(t)
    return t.x, t.y
end

local px, py = make_point{ x = 7, y = 8 }

-- demonstration of prefixexp ':' method call with new object
local obj2 = { n = 0 }
function obj2:inc()
    self.n = self.n + 1
    return self.n
end
obj2:inc()
obj2:inc()

-- label and goto to break out of nested loops
local outer_i = 0
while true do
    outer_i = outer_i + 1
    local inner_j = 0
    while inner_j < 3 do
        inner_j = inner_j + 1
        if outer_i > 2 then
            goto exit_loops
        end
    end
    if outer_i > 5 then break end
end
::exit_loops::

-- local function declared with 'local function Name funcbody'
local function fibonacci(n)
    if n < 2 then return n end
    local a, b = 0, 1
    for _ = 2, n do
        a, b = b, a + b
    end
    return b
end

local fib10 = fibonacci(10)

-- return a table of many values at the end
return {
    version = 1,
    a = a, b = b, c = c,
    t = t,
    M = M,
    cfg = cfg,
    coll = coll,
    fib10 = fib10,
    greeting = greeting,
    sum = sum,
    final = final,
}